<Project>

	<PropertyGroup>
		<UseArtifactsOutput>true</UseArtifactsOutput>
		<ArtifactsPath>$(MSBuildThisFileDirectory).artifacts/</ArtifactsPath>
	</PropertyGroup>

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<RestoreLockedMode>true</RestoreLockedMode>
	</PropertyGroup>

	<PropertyGroup>
		<IsSrcProject>false</IsSrcProject>
		<IsSrcProject Condition="$([System.String]::new('$(MSBuildProjectDirectory)').ToLower().Contains('\src\'))">true</IsSrcProject>
		<IsSrcProject Condition="$([System.String]::new('$(MSBuildProjectDirectory)').ToLower().Contains('/src/'))">true</IsSrcProject>
	</PropertyGroup>

	<PropertyGroup>
		<IsTestProject>false</IsTestProject>
		<IsTestProject Condition="$([System.String]::new('$(MSBuildProjectDirectory)').ToLower().Contains('\tests\'))">true</IsTestProject>
		<IsTestProject Condition="$([System.String]::new('$(MSBuildProjectDirectory)').ToLower().Contains('/tests/'))">true</IsTestProject>
		<TestProjectBaseName Condition="'$(IsTestProject)' == 'true'">$([System.String]::Copy('$(MSBuildProjectName)').Replace('.UnitTests','').Replace('.IntegrationTests','').Replace('.Tests',''))</TestProjectBaseName>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsSrcProject)' == 'true'">
		<IsPackable>true</IsPackable>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Authors>Igor Sinicyn</Authors>
		<Company>CodeMe</Company>
		<Product>CodeMe.ScaffoldCS</Product>
		<PackageProjectUrl>https://github.com/ig-sinicyn/CodeMe.ScaffoldCS</PackageProjectUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsSrcProject)' == 'true'">
		<InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
		<InternalsVisibleTo Include="$(MSBuildProjectName).UnitTests" />
		<InternalsVisibleTo Include="$(MSBuildProjectName).IntegrationTests" />
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<PropertyGroup Condition="'$(IsTestProject)' == 'true'">
		<OutputType>Exe</OutputType>
		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
		<UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsTestProject)' == 'true'">
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
		<PackageReference Include="xunit.v3.mtp-v2" />
		<ProjectReference Include="../../src/$(TestProjectBaseName)/$(TestProjectBaseName).csproj" />
		<Using Include="AwesomeAssertions" />
		<Using Include="Xunit" />
	</ItemGroup>

</Project>