name: Release NuGet Package
on:
  release:
    types: [published] # Triggers when you create a GitHub Release
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run:  dotnet restore
    - name: Build
      run:  dotnet build -c Release -p:Version=${GITHUB_REF_NAME#v} --no-restore
    - name: Run Tests
      run:  dotnet test -c Release --report-trx --results-directory=".artifacts/test-results" --no-build --no-restore
    - name: Pack Nuget
      run:  dotnet pack -c Release -p:Version=${GITHUB_REF_NAME#v} -o .artifacts/packages --no-build --no-restore
    - name: Authenticate with NuGet via OIDC
      uses: NuGet/login@v1
      id:   nuget-login
      with:
        user: ig-sinicyn
    - name: Push Nuget
      run:  dotnet nuget push ".artifacts/packages/**/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --skip-duplicate